language: php
php:
    - '7.2'
    - nightly
services:
    - mysql
before_script:
    - pecl install ast
    - composer install
    - git clone -b develop https://github.com/Orange-Management/Build.git
    - chmod 755 -R Build/
    - ls -l
script:
    - phpunit --version && phpunit --configuration tests/phpunit_no_coverage.xml
    - Build/Hooks/travis.sh
notifications:
    email: false