language: php
php:
    - '7.2'
    - nightly
services:
    - mysql
before_script:
    - pecl install ast
    - composer install
script:
    - vendor/bin/phpunit --configuration tests/phpunit_no_coverage.xml