language: php
dist: trusty
sudo: required
php:
    - '7.2'
    - nightly
addons:
  apt:
    sources:
        - mysql-5.7-trusty
    packages:
        - mysql-server
        - mysql-client
before_script:
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade
    - sudo service mysql restart
    - pecl install ast
    - composer install
script:
    - vendor/bin/phpunit --configuration tests/phpunit_no_coverage.xml